version: '3'
services:
  book-api:
    restart: on-failure
    build: .
    container_name: container_book_api
    command: |
      bash -c 'while !</dev/tcp/pgsql/5432; do sleep 1; done; uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000'
    depends_on:
      - pgsql
    volumes:
      - .:/usr/src/app
      - ./requirements.txt:/usr/src/app/requirements.txt
    ports:
      - '${API_PORT}:${API_PORT}'
    env_file:
      - ./.env
    environment:
      DATABASE_URL: ${PGSQL_URL}
    
  pgsql:
    image: postgres:9.6.2-alpine
    container_name: container_pgsql_db
    volumes:
    - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${PGSQL_USER}
      POSTGRES_PASSWORD: ${PGSQL_PASSWORD}
      POSTGRES_DB: ${PGSQL_DB}